### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by CalvinDaMogul** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#1]

**Comment by CalvinDaMogul** [comment]
# User Story
As a good developer, I should have a nice readme.

# AC
**WHEN** I go to the repo for this project
**THEN** I should see a nice readme
**AND** it should have a title, description, screenshot, instructions to run

# Development
* Modify README.md to have stuff outlined in AC

**Comment by zoeames** [comment]
👍
