### ISSUE TITLE
Create Cards for BrewMasters

### ISSUE THREAD

**Issue by GitMullins** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#10]
# User Story
As a user, I should be able to see the company's employees & their info

# AC
**WHEN** the page loads
**THEN** background color should be light purple
**WHEN** 4 brew master cards should populate the page
**AND** the cards should include a picture & information of the brew master
**AND** the cards should be in columns of 2
**AND** navBar and footer should be linked from card #3 and card #4 

# Development
* index.html with boilerplate html, script tag for main.js, link tag for main.css
* add css link and script tags for bootstrap
* write a for loop to loop through the 4 objects of the `brewMasters` array
* `brewMasters` array should include the following keys: `picture`, `name`, and `responsibilities`.
* print cards to the DOM using `prinToDom` function
* use bootstrap code `"col-6"` to set cards in columns of 2

**Comment by jeressia** [comment]
<img width="524" alt="Screen Shot 2019-03-26 at 7 47 57 PM" src="https://user-images.githubusercontent.com/43094838/55201920-2ee03a00-5193-11e9-86ec-72d635a62dc0.png">

**Comment by zoeames** [comment]
👍
