### ISSUE TITLE
Create Brewery Events

### ISSUE THREAD

**Issue by Lakiajo** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#11]
## User
As a user, I should be able to click on the `Events` link and I should be brought to a separate page with all of the Brewery Events. 

## AC
**WHEN** I click on the Events link the user will be routed to the events page
**THEN** I will be routed to all events for the brewery.
**AND** I should see the event title, description with a photo and Date of event.

##  Development
* Use Javascript to loop an array around several events. Create an event array named `breweryEvents`
* Span each card to width of page. 
* Use the function printToDom to print to the DOM.

**Comment by jeressia** [comment]
<img width="526" alt="Screen Shot 2019-03-26 at 7 51 55 PM" src="https://user-images.githubusercontent.com/43094838/55201024-05251400-518f-11e9-9e07-2b3a428e8702.png">

**Comment by zoeames** [comment]
:+1
