### ISSUE TITLE
Complete Setup

### ISSUE THREAD

**Issue by jeressia** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#2]
# User Story
As a developer, in order have a basic page, I need some starter code.

# AC
**When** the page loads
**THEN** background color should be light purple
**AND** there should be a LARGE "PurpleMonkeyDishwashr"
**AND** there should be a console.log that says "Testing"
**AND** there should be a info colored bootstrap button that says 'Test' to test the functionality of our bootstrap code

# Development
* index.html with boilerplate html, script tag for main.js, link tag for main.css
* main.js - with a console.log
* main.css - with a background color change on the body
* add link and script tags for bootstrap
* add html directory

**Comment by jeressia** [comment]
Color Palette: 
<img width="1262" alt="Screen Shot 2019-03-26 at 8 21 53 PM" src="https://user-images.githubusercontent.com/43094838/55043970-80a78980-5006-11e9-8d6c-dfec760fdbe0.png">

**Comment by zoeames** [comment]
👍
