### ISSUE TITLE
Create a NavBar

### ISSUE THREAD

**Issue by jeressia** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#3]
# User Story

As a user, when I visit any page, I should see a navbar across the top of the page.

# AC
**When** I visit any page
**THEN** links to other pages should be in a horizontal format
**AND** there should be a logo in the left corner

# Development
*use bootstrap navbar
* link the pages using `a href` tag using the labels below
-- Home
-- Brew Masters
-- Brewery Events
-- Available Beers
* `navbar` should be flush to the top of the browser window
* Logo will be left-aligned; links to other pages will be right-aligned

**Comment by jeressia** [comment]
<img width="530" alt="Screen Shot 2019-03-26 at 8 15 25 PM" src="https://user-images.githubusercontent.com/43094838/55043890-2d353b80-5006-11e9-931e-be6fa84ba155.png">

**Comment by GitMullins** [comment]
Bootsrap link for navbar:  https://getbootstrap.com/docs/4.3/components/navbar/

Navbar image code:
```
<!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
  </a>
</nav>
```

Navbar labels/links code:
```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </div>
  </div>
</nav>
```

**Comment by jeressia** [comment]
Monkey Logo:
![logo!](https://user-images.githubusercontent.com/43094838/55122501-3ccb8780-50cd-11e9-942e-89060f38221a.png)

**Comment by zoeames** [comment]
👍   love the logo!!!
