### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by jeressia** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#4]
# User Story
As a user, I should see a footer at the bottom of every page. I should see the name of the company and the address in the center of it. I should see placeholder text in the right-third of this footer that says 'Form Here'

# AC
When I look at a page
Then I should see a footer.
The footer should have the name of the company and the address in the center of it. 
AND there should be an input form to submit my email address to the company's newsletter.

# Development
* create a div called `footer`
* create a div inside `footer` with a class of `col-3 offset-6` i and write information about our company in this column
*create another div inside `footer` with a class `col-3 offset-1` and type placeholder text that says 'Form Here'

**Comment by jeressia** [comment]
Footer Image
<img width="528" alt="Screen Shot 2019-03-26 at 9 19 36 PM" src="https://user-images.githubusercontent.com/43094838/55122647-a2b80f00-50cd-11e9-99bc-856b11cad206.png">

**Comment by zoeames** [comment]
👍
