### ISSUE TITLE
Create a form

### ISSUE THREAD

**Issue by GitMullins** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#6]
# User Story
As a user, I should be able to submit my email address for newsletters from this company.

# AC
**When** I visit a page
**THEN** there should be an `input` element to accept my email address
**AND** I should receive a confirmation/alert that my info has been received

# Development
* create html `input` form element in the bottom right corner of the footer
* `input` element will receive an email address from the user
* create `submit` button which will accept the input value
* alert message confirming the email address has been received will popup upon submittal of the input

**Comment by GitMullins** [comment]
# User Story
As a user, I should be able to submit my email address for newsletters from this company.

# AC
**When** I visit a page
**THEN** there should be an `input` element to accept my email address
**AND** I should receive a confirmation/alert that my info has been received

# Development
* create html `input` form element in the bottom right corner of the footer
* `input` element will receive an email address from the user
* create `submit` button which will accept the input value
* alert message confirming the email address has been received will popup upon submittal of the input

**Comment by jeressia** [comment]
<img width="528" alt="Screen Shot 2019-03-26 at 9 19 36 PM" src="https://user-images.githubusercontent.com/43094838/55046105-5954ba80-500e-11e9-9b2b-3ee04c008ec6.png">

**Comment by zoeames** [comment]
👍

**Comment by Lakiajo** [comment]
Used Modal to generate alert after clicking submit button.
