### ISSUE TITLE
Create Homepage

### ISSUE THREAD

**Issue by jeressia** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#7]
# User Story
As a user, I should be able to navigate to other parts of the website from the homepage and I should see a large image slideshow under the links and the top 3 beers displayed on the page below that.

# AC
**When** the page loads
**THEN** background color should be light purple
**AND** there should be links to brew masters, brewery events, and available beers.
**AND** there should be a large image slideshow underneath the links that spans the entire width of the homepage.
**AND** there should be arrows that allows the user to click to slide to the next picture and indicators to show which slide a user is on.
**AND** there should be 3 cards displaying the current top 3 best selling beers

# Development
* index.html with links to brew masters, brewery events, and available beers
* add link and script tags for bootstrap
* add image carousel from bootstrap with controls and indicators
* create with a forEach loop called `topThree` that loops through `beers` and selects the beers with a key/value pair `rank: 1, 2, or 3`
* create a div called `topThreeDiv` to display best selling beers
* use a printToDom function that prints `topThree` to `topThreeDiv`

**Comment by jeressia** [comment]
<img width="534" alt="Screen Shot 2019-03-26 at 7 44 37 PM" src="https://user-images.githubusercontent.com/43094838/55045787-16461780-500d-11e9-9974-8670147684fc.png">

**Comment by jeressia** [comment]
Carousel Image code (https://getbootstrap.com/docs/4.3/components/carousel/):
```html
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

**Comment by jeressia** [comment]
Bootstrap Links 

https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by zoeames** [comment]
👍

**Comment by jeressia** [comment]
![beers](https://user-images.githubusercontent.com/43094838/55278722-d79ab080-52dd-11e9-978d-16e5314650db.png)

**Comment by jeressia** [comment]
![katlyn-giberson-185277-unsplash](https://user-images.githubusercontent.com/43094838/55280083-a4145200-52ee-11e9-8664-f79cc1dcb0b0.jpg)

**Comment by jeressia** [comment]
![adrien-olichon-777349-unsplash](https://user-images.githubusercontent.com/43094838/55280092-b8f0e580-52ee-11e9-9593-29fcacead1e1.jpg)
