### ISSUE TITLE
Create cards for Available Beers

### ISSUE THREAD

**Issue by CalvinDaMogul** [nss-evening-cohort-9/foundations-group-project-purplemonkeydishwashr#9]
## User 
As a user, I should be able to see a picture of the beer. There will be a button under the image that has the name of the beer on it. When I click on the button under the picture of the beer a small summary of the beer should appear 

## AC 
**WHEN** users come to the page they should be able to see the choices of the beers that we have.  
**THEN** when they click on the button of the selected beer the user should be able to see a summary of the beer 

## Development

* This page will need to have an array called  `beerType`. There will be objects inside the `beerTypes` array that will define the `name`, `descriptionOfBeer`, and `beerIngredients`. Inside the `beerIngredients` object, there will an array of different ingredients.
* Create a `forEach` loop function to display the beers on the page. The function is called `beerBuilder`. Create a `forEach` loop function to display the beer ingredients of each beer. This function is called `ingredientBuilder`.
* The buttons will be made with bootstraps. The buttons  will be connected to the description by the `id`.

**Comment by jeressia** [comment]
<img width="526" alt="Screen Shot 2019-03-26 at 7 51 55 PM" src="https://user-images.githubusercontent.com/43094838/55200984-d4dd7580-518e-11e9-9dce-a34ebf2c7d30.png">

**Comment by jeressia** [comment]
<img width="526" alt="Screen Shot 2019-03-26 at 7 55 12 PM" src="https://user-images.githubusercontent.com/43094838/55201063-40bfde00-518f-11e9-9ff4-a38fa9098647.png">

**Comment by jeressia** [comment]
![NEW](https://user-images.githubusercontent.com/43094838/55201942-43bccd80-5193-11e9-8a3c-4088b4f55fe9.png)

**Comment by CalvinDaMogul** [comment]
## User 
As a user, I should be able to see a picture of the beer. When I click on the button under the picture of the beer a summary of the should appear 

## AC 
**WHEN** users come to the page they should be able to see the choices of the beers we have.  
**THEN** when they click on the button of the selected beer the user should be able to see a summary of the beer 

## Development

* This is page will need to have an `array` to hold the name of the beers and the images. It will be written in dot notation
* Create a `forEach` loop function to display the beers on the page called `beerBuilder`
* The `beerBuilder` function will go through another function called the `init` function

**Comment by CalvinDaMogul** [comment]
Start with this code(https://getbootstrap.com/docs/4.1/components/buttons/):

```
<a class="btn btn-primary" href="#" role="button">Link</a>
<button class="btn btn-primary" type="submit">Button</button>
<input class="btn btn-primary" type="button" value="Input">
<input class="btn btn-primary" type="submit" value="Submit">
<input class="btn btn-primary" type="reset" value="Reset">

```

**Comment by zoeames** [comment]
👍

**Comment by jeressia** [comment]
![1beer](https://user-images.githubusercontent.com/43094838/55278677-7bd02780-52dd-11e9-8043-3dbdae7ef11b.png)
![2beer](https://user-images.githubusercontent.com/43094838/55278678-7d015480-52dd-11e9-9bea-a8832cc1699a.png)
![3beer](https://user-images.githubusercontent.com/43094838/55278679-7ecb1800-52dd-11e9-94d1-99960ee6e9d1.png)
![4beer](https://user-images.githubusercontent.com/43094838/55278680-8094db80-52dd-11e9-848d-faa1662464ba.png)
![5beer](https://user-images.githubusercontent.com/43094838/55278682-82f73580-52dd-11e9-9adc-53299453725e.png)
![6beer](https://user-images.githubusercontent.com/43094838/55278683-84286280-52dd-11e9-9a78-67c61c0c2e8e.png)

**Comment by Lakiajo** [comment]
Reopening. Not Complete.
